version: '3.8'

services:
  unaldatabase:
    image: mariadb:11.3.2
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unal
    ports:
    - "33061:3306"
    volumes:
    - ./dbdata:/var/lib/mysql

  unalapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "80:80"
    - "5173:5173"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - unaldatabase
